# Trigger a release when a tag that looks like a version number is pushed.
on:
  push:
    tags:
      - '[0-9]+.*'

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    permissions:
      contents: write # Needed for creating releases

    strategy:
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
        - target: aarch64-unknown-linux-gnu

    steps:
    - name: Install dependencies
      run: apt-get update && apt-get install -y curl ca-certificates gcc

    - name: Checkout code
      uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable

    - name: Extract release notes
      shell: bash
      run: |
        awk "/# ${GITHUB_REF_NAME}/{flag=1; next} /^$/{flag=0} flag" CHANGELOG.md >REL.md

    - name: Build release binary
      run: cargo build --profile dist --target ${{ matrix.target }}

    - name: Create tarballs
      run: |
        n="wild-linker-${{ github.ref_name }}-${{ matrix.target }}"
        mkdir "$n"
        cp "target/${{ matrix.target }}/dist/wild" "$n"
        cp README.md LICENSE* CHANGELOG.md "$n"
        strip "$n/wild"
        tar zcf $n.tar.gz $n

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: REL.md
        draft: true
        files: |
          wild-linker-*.tar.gz
