# Trigger a release when a tag that looks like a version number is pushed.
on:
  push:
    tags:
      - '[0-9]+.*'

name: Release

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # Needed for creating releases

    strategy:
      matrix:
        include:
        - build: linux
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable

    - name: Extract release notes
      shell: bash
      run: |
        awk "/# ${GITHUB_REF_NAME#}/{flag=1; next} /^$/{flag=0} flag" CHANGELOG.md >REL.md

    - name: Build release binary
      run: cargo build --profile dist --target ${{ matrix.target }}

    - name: Create tarballs
      run: |
        n="wild-linker-${{ github.ref_name }}-${{ matrix.target }}"
        mkdir "$n"
        cp "target/${{ matrix.target }}/dist/wild" "$n"
        strip "$n/wild"
        tar Jcf $n.tar.xz $n

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: REL.md
        draft: true
        files: |
          wild-linker-*.tar.xz
